### PR TITLE
Port to dune

### PR DESCRIPTION
**Pull request by sternenseemann**
I don't have too much experience with dune, but I thought I'd give it a shot.

I'm looking for feedback on the following things:

* I've specified all dependencies previously mentioned in `_tags`. Due to `implicit_transitive_deps` however some of those were unnecessary, e. g. `mirage-crypto`. I feel like it'd be bad style though omitting such dependencies jackline directly depends on. Disabling `implicit_transitive_deps` however would require adding libraries we don't use directly, like `sexplib0`.
* I've had to add version constraints for all dependencies that didn't have them for the dune opam autogeneration to work (it only allows dependencies without constraints if they are associated with a stage :question: :confused: :question: ). For this I just added the version of the package I had installed, mostly the latest version, this is probably not the best option. The packages in question are: `mirage-crypto`, `mirage-crypto-pk`, `lwt`, `astring`, `sexplib`, `hex`, `uchar`, `cstruct-lwt` and `base64`.
* I currently have trouble with `dune utop`, i. e. `ld` can't find some symbols of `notty`. I'm really not sure if this might be caused by my local setup, maybe someone else can test this as well with my changes.
* Anything I've missed :)

### CODE REVIEW

**Comment by hannesm** [comment]
thank you very much for doing this work. I have not yet reviewed in detail, but to answer your questions:
- I'm fine to drop mirage-crypto dependency, since it is not needed (mirage-crypto-pk is used inside of jackline, but not mirage-crypto)
- lower bounds of dependencies: what you did is good (use the most recent ones / the ones installed)
- `dune utop` I'll try to investigate what is up there
- CI failure is on 4.07, and I think we should just drop <4.08 (recent mirage-crypto releases have a lower bound on 4.08, and I don't see much point in keeping backwards compatibility), and at the same time get CI to build 4.08, 4.09, 4.10, soon 4.11 (likely needs to wait until there's camlp4 for 4.11)

I'm not sure I'll be able to review and merge before I leave for a week of vacation, thus sorry if the merge is delayed. I'll definitively work on merging it later in August.

**Comment by sternenseemann** [comment]
No need for a rush, I hope you'll have a nice vacatation :)

I've removed `mirage-crypto`, moved the lower bound for `ocaml` to 4.08 and also tried to change the travis config, I hope this works also in the PR. Also: I was under the impression there was no `camlp4` for ocaml >= 4.09 at all?

For the utop issue: My error is [here](https://gist.github.com/sternenseemann/72fe2fc363a0543f6031f70cef82a9eb), I guess it could be a NixOS-related issue, but I'm not sure what exactly is missing in ld's search path since I'm not to familiar with how OCaml linking and especially this utop feature works.

**Comment by hannesm** [comment]
Thanks, this looks nice. I pushed some minor tweaks, and will merge if CI succeeds.

> I currently have trouble with dune utop, i. e. ld can't find some symbols of notty. I'm really not sure if this might be caused by my local setup, maybe someone else can test this as well with my changes.

For me on a FreeBSD system, `dune utop` works nicely. A `utop` session uses the bytecode (interpreted) OCaml -- and thus needs to load libnotty_unix_stubs.a -- maybe this is not properly installed on your system?

> I was under the impression there was no camlp4 for ocaml >= 4.09 at all?

camlp4 is these days maintained by community (mainly ygrek) under https://github.com/camlp4/camlp4 -- and already a compatibility release for ocaml 4.11 is out (though there was discussion to bury it on discuss.ocaml.org -- eventually jackline should move forward to a different (camlp4-free) xmpp stack (https://github.com/jeffa5/mirage-xmpp).

**Comment by sternenseemann** [comment]
> and already a compatibility release for ocaml 4.11 is out

Alright, I guess I'll have to get on packaging the newer camlp4 versions for NixOS sooner or later.

> and thus needs to load libnotty_unix_stubs.a -- maybe this is not properly installed on your system?

I'll look into it, I suspect our OCaml packages don't install bytecode libs or something?!

**Pull request merged**
